# Docker


# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'pipelines-javascript-docker'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Trace'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Trace'
        repository: 'gokul1247/devops_sample'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: 'devops_sample'
        repositoryName: 'devopstraceability'
        autoCreateRepository: true
